import type { HitStyle } from '../cosmetics';
import { spark, slash, burst, shock, frost, star, prism, vortex, ripple, hex, spiral, shatter, nova, rune, ringburst, ringdance, prismfan } from './basic';
import { shards, cross, sword, swordcross, shuriken, claw, icicle, boulder, quake, meteor, meteorrain, arrow, aim, shield, chain, thorn, thorncrown } from './shard';
import { petal, feather, blossom, sakura, leafstorm, mushroom, wind, tornado, sand, smoke, tide, tsunami, foam, acid, poison, volcano, blizzard } from './nature';
import { lightning, beam, laser, plasma, magnet, portal, blackhole, galaxy, starlight, starfall, aurora, rainbow, holy, sun, moon, atom, dna, sparkle } from './energy';
import { bubble, note, heart, coin, dice, cube, pyramid, gear, sonic, sonar, web, confetti, comet, bomb, firework, flamenova } from './toy';
import { eye, ink, pixelate, glitch, binary, butterfly, phantom } from './odd';
import { pow } from './pow';
import { gzfire } from './gzfire';
import { PLUS_PAINTERS, PLUS_SPAN } from './plus';
import { paintDefault } from './basic';
import type { EffectPainter } from './types';

export type { EffectPainter, HitFlash } from './types';
export { paintDefault };

/** lifetime of each hit-effect style, in seconds */
export const EFFECT_SPAN: Record<HitStyle, number> = {
  ...PLUS_SPAN,
  ring: 0.36,
  spark: 0.4,
  slash: 0.22,
  burst: 0.36,
  shock: 0.4,
  frost: 0.36,
  petal: 0.52,
  lightning: 0.28,
  star: 0.42,
  prism: 0.54,
  vortex: 0.54,
  shards: 0.44,
  ripple: 0.56,
  confetti: 0.58,
  cross: 0.3,
  hex: 0.5,
  spiral: 0.5,
  web: 0.46,
  bubble: 0.6,
  feather: 0.62,
  comet: 0.4,
  shatter: 0.36,
  smoke: 0.66,
  sonic: 0.42,
  gear: 0.54,
  nova: 0.5,
  rune: 0.6,
  bomb: 0.44,
  flamenova: 0.48,
  icicle: 0.42,
  sword: 0.26,
  claw: 0.32,
  meteor: 0.5,
  beam: 0.34,
  poison: 0.6,
  note: 0.62,
  heart: 0.66,
  coin: 0.5,
  dice: 0.46,
  arrow: 0.4,
  shield: 0.44,
  chain: 0.52,
  thorn: 0.44,
  blossom: 0.5,
  cube: 0.44,
  pyramid: 0.5,
  aim: 0.4,
  sonar: 0.5,
  wind: 0.46,
  sand: 0.5,
  acid: 0.5,
  sun: 0.46,
  moon: 0.5,
  eye: 0.46,
  portal: 0.52,
  dna: 0.56,
  atom: 0.52,
  sparkle: 0.46,
  ink: 0.44,
  firework: 0.72,
  ringburst: 0.44,
  swordcross: 0.34,
  shuriken: 0.46,
  boulder: 0.5,
  quake: 0.5,
  tornado: 0.6,
  blizzard: 0.56,
  volcano: 0.62,
  tsunami: 0.56,
  aurora: 0.6,
  starlight: 0.52,
  galaxy: 0.62,
  blackhole: 0.6,
  meteorrain: 0.66,
  rainbow: 0.56,
  laser: 0.3,
  plasma: 0.46,
  magnet: 0.5,
  foam: 0.56,
  leafstorm: 0.6,
  sakura: 0.62,
  mushroom: 0.62,
  pixelate: 0.5,
  glitch: 0.4,
  binary: 0.56,
  ringdance: 0.6,
  butterfly: 0.62,
  phantom: 0.54,
  holy: 0.5,
  thorncrown: 0.5,
  tide: 0.5,
  starfall: 0.56,
  prismfan: 0.5,
  pow: 0.5,
  gzfire: 0.5,
};

/** every style that has a bespoke painter; the rest use `paintDefault` */
export const EFFECT_PAINTERS: Partial<Record<HitStyle, EffectPainter>> = {
  ...PLUS_PAINTERS,
  acid,
  aim,
  arrow,
  atom,
  aurora,
  beam,
  binary,
  blackhole,
  blizzard,
  blossom,
  bomb,
  boulder,
  bubble,
  burst,
  butterfly,
  chain,
  claw,
  coin,
  comet,
  confetti,
  cross,
  cube,
  dice,
  dna,
  eye,
  feather,
  firework,
  flamenova,
  foam,
  frost,
  galaxy,
  gear,
  glitch,
  heart,
  hex,
  holy,
  icicle,
  ink,
  laser,
  leafstorm,
  lightning,
  magnet,
  meteor,
  meteorrain,
  moon,
  mushroom,
  note,
  nova,
  petal,
  phantom,
  pixelate,
  plasma,
  poison,
  portal,
  pow,
  gzfire,
  prism,
  prismfan,
  pyramid,
  quake,
  rainbow,
  ringburst,
  ringdance,
  ripple,
  rune,
  sakura,
  sand,
  shards,
  shatter,
  shield,
  shock,
  shuriken,
  slash,
  smoke,
  sonar,
  sonic,
  spark,
  sparkle,
  spiral,
  star,
  starfall,
  starlight,
  sun,
  sword,
  swordcross,
  thorn,
  thorncrown,
  tide,
  tornado,
  tsunami,
  volcano,
  vortex,
  web,
  wind,
};
